name: flutter_share
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  image_downloader: ^0.31.0
  logger: ^1.1.0
  permission_handler: ^8.3.0
  share_plus: ^3.0.4
  stacked: ^2.2.8

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.7
flutter:
  uses-material-design: true
